[package]
name = "fers"
version = "0.1.0"
authors = ["Aumy <46275902+AumyF@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"
anyhow = "1.0.41"
thiserror = "1.0.25"
